server.port=8080

# Project root should point to the Packet_analyzer-main folder.
packet.analyzer.project-root=../..
packet.analyzer.executable=dpi_engine.exe
packet.analyzer.input-pcap=test_dpi.pcap
packet.analyzer.output-pcap=output.pcap
packet.analyzer.report-json=frontend/dashboard/report.json
